apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin
    labels:
        tier: admin
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: ft_services
            tier: admin
    template:
        metadata:
            labels:
                app: ft_services
                tier: admin
        spec:
            restartPolicy: Always
            containers:
                -   name: phpmyadmin
                    image: my-admin
                    imagePullPolicy: Never
                    env:
                        - name: PMA_HOST
                          value: mysql
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
    labels:
        tier: admin
spec:
    type: NodePort
    selector:
        app: ft_services
        tier: admin
    ports:
        -   targetPort: 80
            port: 5000