apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
    labels:
        tier: grafana
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: ft_services
            tier: grafana
    template:
        metadata:
            labels:
                app: ft_services
                tier: grafana
        spec:
            restartPolicy: Always
            containers:
                -   name: grafana
                    image: my-grafana
                    imagePullPolicy: Never
                    env:
                        -   name: GF_SERVER_ROOT_URL
                            value: "%(protocol)s://%(domain)s:/grafana/"
                        -   name: GF_SERVER_DOMAIN
                            value: "localhost"
---
apiVersion: v1
kind: Service
metadata:
    name: grafana
    labels:
        tier: grafana
spec:
    type: NodePort
    selector:
        app: ft_services
        tier: grafana
    ports:
        -   port: 3000
            targetPort: 3000