apiVersion: apps/v1
kind: Deployment
metadata:
    name: influxdb
    labels:
        tier: influx
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: ft_services
            tier: influx
    template:
        metadata:
            labels:
                app: ft_services
                tier: influx
        spec:
            restartPolicy: Always
            containers:
                -   name: influxdb
                    imagePullPolicy: Never
                    image: my-influx
                    volumeMounts:
                        -   name:  influx-storage
                            mountPath: /var/lib/influxdb
            volumes:
            -   name: influx-storage
                persistentVolumeClaim:
                    claimName: influx-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb
    labels:
        tier: influx
spec:
    type: NodePort
    selector:
        app: ft_services
        tier: influx
    ports:
        -   targetPort: 8086
            port: 8086
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: influx-pv
spec:
    storageClassName: local
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/mnt/base/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: influx-pvc
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: local
    resources:
        requests:
            storage: 1Gi