apiVersion: v1
kind: Service
metadata:
    name: telegraf
    labels:
        tier: telegraf
spec:
    selector:
        app: ft_services
        tier: telegraf
    clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf
    labels:
        app: ft_services
        tier: telegraf
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: ft_services
            tier: telegraf
    template:
        metadata:
            labels:
                app: ft_services
                tier: telegraf
        spec:
            restartPolicy: Always
            serviceAccountName: telegraf
            containers:
            -   image: my-telegraf
                name: telegraf
                imagePullPolicy: Never
                env:
                -   name: MINIKUBE_IP
                    valueFrom:
                        secretKeyRef:
                            name: ip-secret
                            key: ip
            volumes:
                -   name: ip-secret
                    secret:
                        secretName: ip-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: telegraf
    namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: telegraf
subjects:
-   kind: ServiceAccount
    name: telegraf
    namespace: default
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io