apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        tier: wordpress
spec:
    ports:
        -   targetPort: 80
            port: 5050
    selector:
        app: ft_services
        tier: wordpress
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
    labels:
        app: ft_services
        tier: wordpress
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: ft_services
            tier: wordpress
    template:
        metadata:
            labels:
                app: ft_services
                tier: wordpress
        spec:
            restartPolicy: Always
            containers:
            -   image: my-wp
                name: wordpress
                imagePullPolicy: Never
                env:
                -   name: WORDPRESS_DB_HOST
                    value: mysql
                -   name: WORDPRESS_DB_USER
                    value: wp-user
                -   name: WORDPRESS_DB_PASSWORD
                    value: wordpress